//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYM
{
    using System;
    using System.Collections.Generic;
    
    public partial class cenovnik
    {
        public int cena { get; set; }
        public string tip { get; set; }
        public int IDCena { get; set; }
        public string poslednjePromene { get; set; }
    
        public virtual termin termin { get; set; }
    }
}
