//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYM.klase
{
    using System;
    using System.Collections.Generic;
    
    public partial class cenovnik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cenovnik()
        {
            this.stampanjeracunas = new HashSet<stampanjeracuna>();
        }
    
        public int cena { get; set; }
        public string tip { get; set; }
        public int IDCena { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<stampanjeracuna> stampanjeracunas { get; set; }
    }
}
