//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYM.klase
{
    using System;
    using System.Collections.Generic;
    
    public partial class korisnik
    {
        public string IDKorisnika { get; set; }
        public string sifra { get; set; }
        public string KorisnickoIme { get; set; }
        public string tip { get; set; }
    
        public virtual osoba osoba { get; set; }
    }
}
