//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYM.klase
{
    using System;
    using System.Collections.Generic;
    
    public partial class osoba
    {
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public Nullable<int> brTelefona { get; set; }
        public string adresa { get; set; }
        public string email { get; set; }
        public string pol { get; set; }
        public string JMBG { get; set; }
    
        public virtual clan clan { get; set; }
        public virtual korisnik korisnik { get; set; }
        public override string ToString()
        {
            return this.JMBG + " " + this.Ime + " " + this.Prezime + " " + this.email + " " + this.pol + " " + this.adresa + " " + this.brTelefona;
        }
    }
}
