//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYM
{
    using Klase;
    using System;
    using System.Collections.Generic;
    using System.Data;

    public partial class rezultati
    {
        public double visina { get; set; }
        public double tezina { get; set; }
        public double ruke { get; set; }
        public double noge { get; set; }
        public double struk { get; set; }
        public string JMBG1 { get; set; }
        public Nullable<double> visina_epic { get; set; }
        public Nullable<double> tezina_epic { get; set; }
        public Nullable<double> ruke_epic { get; set; }
        public Nullable<double> noge_epic { get; set; }
        public Nullable<double> struk_epic { get; set; }
        public string vremeUnosa { get; set; }
        public string vremeUnosa_epic { get; set; }
        public string ime { get; set; }
    
        public virtual clan clan { get; set; }
        public override string ToString()
        {
            return this.ime + " " + this.visina + " " + this.tezina + " " + this.ruke + " " + this.noge + " " + this.struk + " " + this.JMBG1;
        }
        public rezultati()
        {
            this.visina = 0;
            this.tezina = 0;
            this.ruke = 0;
            this.noge = 0;
            this.struk = 0;

            this.JMBG1 = null;
            this.visina_epic = 0;
            this.tezina_epic = 0;
            this.ruke_epic = 0;
            this.noge_epic = 0;
            this.struk_epic = 0;
            this.vremeUnosa = null;
            this.vremeUnosa_epic = null;
            this.ime = null;
        }

        public rezultati(float visina, float tezina, float ruke, float noge, float struk, string JMBG1, float visina_epic, float tezina_epic, float ruke_epic, float noge_epic, float struk_epic, string vremeUnosa, string vremeUnosa_epic, string ime)
        {
            this.visina = visina;
            this.tezina = tezina;
            this.ruke = ruke;
            this.noge = noge;
            this.struk = struk;
            this.JMBG1 = JMBG1;
            this.visina_epic = visina_epic;
            this.tezina_epic = tezina_epic;
            this.ruke_epic = ruke_epic;
            this.noge_epic = noge_epic;
            this.struk_epic = struk_epic;
            this.vremeUnosa = vremeUnosa;
            this.vremeUnosa_epic = vremeUnosa_epic;
            this.ime = ime;
        }

        public DataTable listBox1()
        {
            DataTable dt = Bazaa.listBox1(this);
            return dt;
        }
    }
}

