//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYM.klase
{
    using System;
    using System.Collections.Generic;
    
    public partial class rezultati
    {
        public string ime { get; set; }
        public double visina { get; set; }
        public double tezina { get; set; }
        public double ruke { get; set; }
        public double noge { get; set; }
        public double struk { get; set; }
        public string JMBG1 { get; set; }
    
        public virtual clan clan { get; set; }
        public virtual statistika statistika { get; set; }
    }
}
