//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYM
{
    using System;
    using System.Collections.Generic;
    
    public partial class termin
    {
        public string datum { get; set; }
        public int IDtermina { get; set; }
        public string vreme { get; set; }
        public string Tiptreninga { get; set; }
        public string ImeiPrezime { get; set; }
        public int arhivirano { get; set; }
    
        public virtual cenovnik cenovnik { get; set; }

        public termin()
        {
            this.datum = null;
            this.IDtermina = 0;
            this.vreme = null;
            this.Tiptreninga = null;
            this.ImeiPrezime = null;
            this.arhivirano = 0;
        }
        public termin(String datum, String IDtermina, String vreme, String Tiptreninga, String ImeiPrezime, String arhivirano)
        {
            this.datum = null;
            this.IDtermina = 0;
            this.vreme = null;
            this.Tiptreninga = null;
            this.ImeiPrezime = null;
            this.arhivirano = 0;
        }
    }
}
